export interface SelectPatientResponse {
  doctorId: string,
  displayName: string,
  specializationCodes: string[],
  specializationTitles:  string[],
  telegramUsername: string,
  degrees: string,
  experienceYears: 0,
  languages: string,
  bio: string,
  focusAreas: string,
  acceptingNewPatients: boolean,
  location: string,
  contactPolicy: string,
  avatarUrl: string,
  registrationStatus: number,
  lastSelectedPatientId: string,
  verified: boolean,
  rating: number
}
