export const Environment = {
  production: false,
  apiUrl: 'https://api.muk.i234.me:443',
  specializationUrlPath: '/v1/reference/specializations',
  registrationUrlPath: '/v1/registration',
  patientsUrlPath: '/v1/patients',
  patientsChatUrlPath: '/v1/patients/{patientId}/chat/conversations',
  patientsChatCurrentUrlPath: '/v1/patients/{patientId}/chat/current',
  patientsChatCurrentTurnsUrlPath: '/v1/patients/{patientId}/chat/current/turns',
  patientsChatSummaryUrlPath: '/v1/patients/{patientId}/chat/conversations/{conversationId}/summary',
  staticContentUrlPath: '/v1/static-content',
  meUrlPath: '/v1/me',
  meChatGeneralUrlPath: '/v1/me/chat/general',
  authUrlPath: '/v1/auth',
  botUrlPath: '/v1/bot',
  botChatUrlPath: '/v1/bot/chat/general',
};
