services:
  enrichment-service-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ANGULAR_CONFIGURATION: ${ANGULAR_CONFIGURATION:-production}
    container_name: enrichment-service-ui
    ports:
      - "8081:80"
    restart: unless-stopped
